name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl keepalive function without auth
        run: |
          curl -s https://pshuqmmkxmwgmvhuaujn.functions.supabase.co/keepalive
